// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, cleanup } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Credit from '../../../components/Credit';

// This is the test suite for the Credit component
describe('Credit component', () => {
  // Clean up after each test
  afterEach(cleanup);

  // Test case 1: Render without crashing
  test('renders without crashing', () => {
    const { getByText } = render(<Credit />);
    expect(getByText('Coded by')).toBeInTheDocument();
  });

  // Test case 2: Validate the class name of the outer div
  test('has correct class for styling', () => {
    const { container } = render(<Credit />);
    expect(container.firstChild).toHaveClass('credit');
  });

  // Test case 3: Validate anchor elements and their href attributes
  test('contains correct links', () => {
    const { getByText } = render(<Credit />);
    expect(getByText('Chaimae Lamirine').closest('a')).toHaveAttribute('href', 'https://www.shecodes.io/graduates/73033-chaimae-lamirine');
    expect(getByText('Open sourced on Github.').closest('a')).toHaveAttribute('href', 'https://github.com/shemmee/React-Weather-App');
  });
});

