// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// Credit.test.js

import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Credit from '../../../components/Credit.js';

describe('Credit component', () => {
  test('it renders without crashing', () => {
    render(<Credit />);
    const creditElement = screen.getByText(/coded by/i);
    expect(creditElement).toBeInTheDocument();
  });

  test('it contains correct links', () => {
    render(<Credit />);
    const githubLink = screen.getByText('Open sourced on Github.').closest('a');
    const sheCodesLink = screen.getByText('Chaimae Lamirine').closest('a');
    expect(githubLink).toHaveAttribute('href', 'https://github.com/shemmee/React-Weather-App');
    expect(sheCodesLink).toHaveAttribute('href', 'https://www.shecodes.io/graduates/73033-chaimae-lamirine');
  });

  // Additional tests can be added here for different scenarios
});

